// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-OCuGWN3VM3nLXTfla3PBdtO_KSR0eA8',
    appId: '1:298366329874:web:4145c29a479e9d9d6724cb',
    messagingSenderId: '298366329874',
    projectId: 'vibee-479c7',
    authDomain: 'vibee-479c7.firebaseapp.com',
    storageBucket: 'vibee-479c7.firebasestorage.app',
    measurementId: 'G-HXYF4LCY5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT30RvqAtB330t3Gmty7TNeSUtpbDnJ-M',
    appId: '1:298366329874:android:2edeffc22091fc046724cb',
    messagingSenderId: '298366329874',
    projectId: 'vibee-479c7',
    storageBucket: 'vibee-479c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7N6kiv30_f2wExlmX_UH2wLAC9WNm-EM',
    appId: '1:298366329874:ios:029eaab74ac0d15a6724cb',
    messagingSenderId: '298366329874',
    projectId: 'vibee-479c7',
    storageBucket: 'vibee-479c7.firebasestorage.app',
    androidClientId: '298366329874-ekvhj02h3dkb2qveqj7nb6qp2cig2vjm.apps.googleusercontent.com',
    iosClientId: '298366329874-0iubc1ul8iv2ja74agapd4lb5spur8nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7N6kiv30_f2wExlmX_UH2wLAC9WNm-EM',
    appId: '1:298366329874:ios:029eaab74ac0d15a6724cb',
    messagingSenderId: '298366329874',
    projectId: 'vibee-479c7',
    storageBucket: 'vibee-479c7.firebasestorage.app',
    androidClientId: '298366329874-ekvhj02h3dkb2qveqj7nb6qp2cig2vjm.apps.googleusercontent.com',
    iosClientId: '298366329874-0iubc1ul8iv2ja74agapd4lb5spur8nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-OCuGWN3VM3nLXTfla3PBdtO_KSR0eA8',
    appId: '1:298366329874:web:cd5f567de2f4449a6724cb',
    messagingSenderId: '298366329874',
    projectId: 'vibee-479c7',
    authDomain: 'vibee-479c7.firebaseapp.com',
    storageBucket: 'vibee-479c7.firebasestorage.app',
    measurementId: 'G-1KZ1MR650R',
  );

}